e-test-svalerdos:
  host: "p-test-svalerdos-proxy-g0uz3s.5sc6y6-2.usa-e2.cloudhub.io/"
  port: "443"
  path:
    accounts: "/accounts"
  credentials:
    client_id: "![1DuBUoekpu2HGd/UHJq4RoZP5izV5K7QZY6BV90EyCQMODPkQlHJyg==]" 
    client_secret: "![XDr5cw0gNYwhCKywK2gwVA9EEp/td3QhdBOoxB7zPZ6jPvGZN2ptrQ==]" 