name: Build and Deploy to Sandbox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <servers>
            <server>
              <id>anypoint-exchange-v3</id>
              <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
              <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
            </server>
          </servers>
        </settings>" > ~/.m2/settings.xml
    - name: Build with Maven
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        # Eliminar dependencias problem치ticas
        rm -rf ~/.m2/repository/com/github/everit-org
        rm -rf ~/.m2/repository/org/everit
        
        # Compilar omitiendo pruebas y forzando actualizaci칩n
        mvn -B clean package --file pom.xml -Ddecryption.key="${ENCRYPTION_KEY}" -Dmaven.test.skip=true
    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <servers>
            <server>
              <id>anypoint-exchange-v3</id>
              <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
              <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
            </server>
          </servers>
        </settings>" > ~/.m2/settings.xml
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: target/
    - name: Deploy to Sandbox
      env:
        ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        # Desplegar directamente con par치metros adicionales
        echo "Desplegando la aplicaci칩n con runtime 4.9.3 y Java 17..."
        mvn deploy -DmuleDeploy \
        -DskipDeploymentVerification=true \
        -DskipMuleVersionCompatibilityCheck=true \
        -Danypoint.username="${ANYPOINT_USERNAME}" \
        -Danypoint.password="${ANYPOINT_PASSWORD}" \
        -Ddecryption.key="${ENCRYPTION_KEY}" \
        -Dmule.artifact=$(ls target/*.jar | head -1) \
        -Ddeployment.target=Cloudhub-US-East-2 \
        -Dapp.runtime=4.9.3 \
        -Djava.version=17







        