name: Build and Deploy e-test-svalerdos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <servers>
            <server>
              <id>anypoint-exchange-v3</id>
              <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
              <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
            </server>
            <server>
              <id>mulesoft-releases</id>
              <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
              <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
            </server>
            <server>
              <id>central</id>
              <username></username>
              <password></password>
            </server>
          </servers>
        </settings>" > ~/.m2/settings.xml
    - name: Build with Maven
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        # Eliminar dependencias problemáticas
        rm -rf ~/.m2/repository/com/github/everit-org
        rm -rf ~/.m2/repository/org/everit
        rm -rf ~/.m2/repository/com/github/everit-org.json-schema
        rm -rf ~/.m2/repository/org/everit/json
        
        # Compilar omitiendo pruebas y forzando actualización
        mvn -U -B clean package --file pom.xml -Ddecryption.key="${ENCRYPTION_KEY}" -Dencryption.key="${ENCRYPTION_KEY}" -Dmaven.test.skip=true
    - name: Upload artifact 
      uses: actions/upload-artifact@v4
      with:
          name: artifacts
          path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <servers>
            <server>
              <id>anypoint-exchange-v3</id>
              <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
              <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
            </server>
            <server>
              <id>mulesoft-releases</id>
              <username>${{ secrets.ANYPOINT_PLATFORM_USERNAME }}</username>
              <password>${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}</password>
            </server>
            <server>
              <id>central</id>
              <username></username>
              <password></password>
            </server>
          </servers>
        </settings>" > ~/.m2/settings.xml
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: target/
    - name: Deploy to Sandbox
      env:
        ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_PLATFORM_USERNAME }}
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PLATFORM_PASSWORD }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        # Mostrar el artefacto que se va a desplegar
        echo "Artefacto a desplegar:"
        ls -la target/
        
        # Desplegar con método alternativo
        echo "Desplegando la aplicación con método alternativo..."
        mvn -U mule:deploy \
        -Dmule.artifact=$(ls target/*.jar | head -1) \
        -Danypoint.username="${ANYPOINT_USERNAME}" \
        -Danypoint.password="${ANYPOINT_PASSWORD}" \
        -Ddecryption.key="${ENCRYPTION_KEY}" \
        -Dencryption.key="${ENCRYPTION_KEY}" \
        -Dapp.runtime=4.9.3 \
        -Dapp.name=e-test-svalerdos \
        -Denv=Sandbox \
        -Ddeployment.target=Cloudhub-US-East-2 \
        -DdeploymentType=CLOUDHUB_V2 \
        -DskipDeploymentVerification=true \
        -DskipMuleVersionCompatibilityCheck=true \
        -Djava.version=17 \
        -Dmule.verbose.exceptions=true \
        -Dmule.verbose.deployment=true \
        -X